# Generated by Django 3.0.7 on 2020-09-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('address', models.TextField(blank=True, max_length=500, verbose_name='address')),
                ('phone', models.TextField(blank=True, max_length=50, verbose_name='phone')),
                ('city', models.CharField(choices=[('Accra', 'Accra'), ('Kumasi', 'Kumasi'), ('Tamale', 'Tamale'), ('Takoradi', 'Takoradi'), ('Sunyani', 'Sunyani'), ('Cape_Coast', 'Cape Coast'), ('Obuasi', 'Obuasi'), ('Teshie', 'Teshie'), ('Koforidua', 'Koforidua'), ('Wa', 'Wa'), ('Bolgatanga', 'Bolgatanga')], default='', max_length=50, verbose_name='city')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
