# Generated by Django 3.0.7 on 2020-09-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.CharField(choices=[('Morning', 'Morning'), ('Midmorning', 'Midmorning'), ('Afternoon', 'Afternoon')], max_length=30)),
                ('speaker', models.CharField(max_length=50)),
                ('room_capacity', models.PositiveIntegerField()),
                ('topic', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=100)),
            ],
        ),
    ]
